### PR TITLE
Add support for FreeCAD 0.22, Path -> CAM

### PR DESCRIPTION
**Pull request by jbaehr**
Recently, the Path workbench was renamed to CAM.

This change supports the current dev version of FreeCAD (0.22, which probably becomes 1.0) while maintaining compatibility with the current stable release 0.21

### CODE REVIEW

**Comment by jbaehr** [comment]
I saw it too late -- this PR is very similar to #53.

**Comment by dubstar-04** [comment]
Would you mind testing #53? If it works I will merge it and your other pr.

**Comment by jbaehr** [comment]
> Would you mind testing #53?

Yes, it works alike -- tested with FreeCAD 0.22.0dev.37578, build locally on macOS

**Comment by dubstar-04** [comment]
fixed with #57

**Pull request closed without merging**
